services:
  app:
    build: blucab
    container_name: django
    ports:
      - '8000:8000'
    volumes:
      - ./app_db:/app/db
      - ./app_covers:/app/main/static/main/cover
      - ./app_import:/app/import
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env.dev
    #environment:
    #  - DEBUG=False
